from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"missing expected block: {label}")
    return text.replace(old, new, 1)

# Scalable tactical bathymetry and abyss presentation.
path = Path("Game/Environment/ScalableEnvironmentPresentation.h")
text = path.read_text(encoding="utf-8")
text = replace_once(
    text,
    '#include "Engine/Render/ModelDraw.h"\n',
    '#include "Engine/Render/ModelDraw.h"\n#include "Game/WaterPresentation.h"\n',
    "water presentation include")
text = replace_once(
    text,
    '''inline constexpr std::array<StrategicSeabedPresentationPoint, 17> M5StrategicSeabedProfile{{\n    {-12\'000.0F, -286.0F}, {-10\'500.0F, -238.0F}, {-9\'000.0F, -322.0F}, {-7\'500.0F, -264.0F},\n    {-6\'000.0F, -374.0F}, {-4\'500.0F, -302.0F}, {-3\'000.0F, -346.0F}, {-1\'500.0F, -248.0F},\n    {0.0F, -330.0F}, {1\'500.0F, -278.0F}, {3\'000.0F, -402.0F}, {4\'500.0F, -316.0F},\n    {6\'000.0F, -232.0F}, {7\'500.0F, -358.0F}, {9\'000.0F, -294.0F}, {10\'500.0F, -438.0F},\n    {12\'000.0F, -340.0F}}};''',
    '''inline constexpr std::array<StrategicSeabedPresentationPoint, 28> M5StrategicSeabedProfile{{\n    // Wide context deliberately descends into deep ocean away from the authored local combat region.\n    {-12\'000.0F, -2\'000.0F}, {-9\'000.0F, -1\'600.0F}, {-6\'000.0F, -1\'200.0F},\n    {-4\'000.0F, -900.0F}, {-2\'500.0F, -650.0F}, {-1\'500.0F, -450.0F}, {-800.0F, -300.0F},\n    // The centre reproduces the accepted M3 authored profile knots exactly so local -> tactical LOD does not\n    // move the visible seabed under the player.\n    {-400.0F, -160.0F}, {-320.0F, -155.0F}, {-250.0F, -150.0F},\n    {-180.0F, -125.0F}, {-130.0F, -120.0F}, {-90.0F, -132.0F},\n    {-45.0F, -140.0F}, {-20.0F, -205.0F}, {0.0F, -220.0F},\n    {80.0F, -220.0F}, {120.0F, -205.0F}, {180.0F, -180.0F},\n    {260.0F, -170.0F}, {400.0F, -165.0F},\n    {800.0F, -300.0F}, {1\'500.0F, -480.0F}, {2\'500.0F, -700.0F},\n    {4\'000.0F, -950.0F}, {6\'000.0F, -1\'200.0F}, {9\'000.0F, -1\'600.0F},\n    {12\'000.0F, -2\'000.0F}}};''',
    "strategic profile")
start = text.index('[[nodiscard]] inline std::expected<std::vector<DeepWaterAbyssPresentationBand>, std::string>\nBuildDeepWaterAbyssPresentationBands')
end = text.index('\n[[nodiscard]] inline std::expected<Assets::ModelAsset, std::string>\nBuildStrategicSeabedPresentationModel()', start)
text = text[:start] + '''[[nodiscard]] inline std::expected<std::vector<DeepWaterAbyssPresentationBand>, std::string>\nBuildDeepWaterAbyssPresentationBands(const float gameplayBandBottomViewportY)\n{\n    if (!std::isfinite(gameplayBandBottomViewportY))\n    {\n        return std::unexpected("deep-water presentation boundary is not finite");\n    }\n\n    constexpr float EdgeEpsilon = 1.0e-4F;\n    const float top = std::clamp(gameplayBandBottomViewportY, 0.0F, 1.0F);\n    if (top >= 1.0F - EdgeEpsilon)\n    {\n        return std::vector<DeepWaterAbyssPresentationBand>{};\n    }\n\n    // The former four broad rectangles read as a second flat seabed. Many shallow steps start at the exact\n    // normal underwater clear colour and smoothly approach deep-ocean darkness. A future shader may replace\n    // this renderer-neutral fallback without changing bathymetry or simulation authority.\n    constexpr std::size_t BandCount = 32U;\n    constexpr Render::RgbaColor DeepAbyssColor{0.0008F, 0.0080F, 0.0220F, 1.0F};\n    const Render::RgbaColor shallowColor = M2UnderwaterBackgroundColor;\n    const float height = (1.0F - top) / static_cast<float>(BandCount);\n    const auto lerpColor = [](const float first, const float second, const float t) noexcept\n    {\n        return first + (second - first) * t;\n    };\n\n    std::vector<DeepWaterAbyssPresentationBand> result;\n    result.reserve(BandCount);\n    for (std::size_t index = 0U; index < BandCount; ++index)\n    {\n        const float linearT = BandCount > 1U\n            ? static_cast<float>(index) / static_cast<float>(BandCount - 1U)\n            : 1.0F;\n        const float smoothT = linearT * linearT * (3.0F - 2.0F * linearT);\n        const float bandTop = top + static_cast<float>(index) * height;\n        const float bandBottom = index + 1U == BandCount\n            ? 1.0F\n            : top + static_cast<float>(index + 1U) * height;\n        result.push_back(DeepWaterAbyssPresentationBand{\n            .viewport = {.left = 0.0F, .top = bandTop, .right = 1.0F, .bottom = bandBottom},\n            .color = {\n                lerpColor(shallowColor.r, DeepAbyssColor.r, smoothT),\n                lerpColor(shallowColor.g, DeepAbyssColor.g, smoothT),\n                lerpColor(shallowColor.b, DeepAbyssColor.b, smoothT),\n                1.0F}});\n    }\n    return result;\n}\n''' + text[end:]
path.write_text(text, encoding="utf-8")

# The current M5 combat region is a known shallow/continental region; preserve bathymetry through tactical LOD.
path = Path("Game/PhysicalPlayground.cpp")
text = path.read_text(encoding="utf-8")
text = replace_once(
    text,
    '''            // Generic M5 has no authoritative wide-area bathymetry. Do not manufacture a seabed merely because\n            // the camera zoomed out. Explicit future/mission-authored bathymetry can opt into the temporary\n            // strategic profile at this boundary without changing physics/navigation/acoustics.\n            constexpr bool M5GenericWideAreaBathymetryKnown = false;\n            if (UseStrategicSeabedPresentation(camera->width, M5GenericWideAreaBathymetryKnown))\n            {\n                strategicSeabedPresentationDraws = strategicSeabedDraws_;\n            }\n''',
    '''            // This concrete M5 combat playground owns an authored tactical-context bathymetry extension whose\n            // central knots match the accepted local M3 seabed. It is presentation-only (no Jolt/nav/acoustic\n            // authority) but zoom must not make a known shallow seabed disappear. Other future regions may\n            // explicitly choose unknown/deep bathymetry and fall through to the abyss presentation.\n            constexpr bool M5CombatRegionWideAreaBathymetryKnown = true;\n            if (UseStrategicSeabedPresentation(camera->width, M5CombatRegionWideAreaBathymetryKnown))\n            {\n                strategicSeabedPresentationDraws = strategicSeabedDraws_;\n            }\n            else\n            {\n                // Flora is rooted in the local seabed profile. Once neither detailed nor tactical-context\n                // bathymetry is rendered, retaining it would leave plants visibly suspended in deep water.\n                floraPresentationDraws = {};\n            }\n''',
    "M5 region bathymetry selection")
path.write_text(text, encoding="utf-8")

# Regression coverage.
path = Path("Tests/M5ScalableEnvironmentPresentationChecks.h")
text = path.read_text(encoding="utf-8")
text = replace_once(
    text,
    '''    if (!abyssBands || abyssBands->size() != 4U || !noAbyssBands || !noAbyssBands->empty() ||\n        invalidAbyssBands.has_value() ||\n        std::abs(abyssBands->front().viewport.top - 0.60F) > 0.0001F ||\n        std::abs(abyssBands->back().viewport.bottom - 1.0F) > 0.0001F)\n    {\n        return false;\n    }\n    for (std::size_t index = 1U; index < abyssBands->size(); ++index)\n    {\n        if (std::abs((*abyssBands)[index - 1U].viewport.bottom - (*abyssBands)[index].viewport.top) > 0.0001F ||\n            (*abyssBands)[index].color.r > (*abyssBands)[index - 1U].color.r ||\n            (*abyssBands)[index].color.g > (*abyssBands)[index - 1U].color.g ||\n            (*abyssBands)[index].color.b > (*abyssBands)[index - 1U].color.b)\n        {\n            return false;\n        }\n    }\n''',
    '''    if (!abyssBands || abyssBands->size() != 32U || !noAbyssBands || !noAbyssBands->empty() ||\n        invalidAbyssBands.has_value() ||\n        std::abs(abyssBands->front().viewport.top - 0.60F) > 0.0001F ||\n        std::abs(abyssBands->back().viewport.bottom - 1.0F) > 0.0001F ||\n        std::abs(abyssBands->front().color.r - M2UnderwaterBackgroundColor.r) > 0.0001F ||\n        std::abs(abyssBands->front().color.g - M2UnderwaterBackgroundColor.g) > 0.0001F ||\n        std::abs(abyssBands->front().color.b - M2UnderwaterBackgroundColor.b) > 0.0001F)\n    {\n        return false;\n    }\n    for (std::size_t index = 1U; index < abyssBands->size(); ++index)\n    {\n        const auto& previous = (*abyssBands)[index - 1U];\n        const auto& current = (*abyssBands)[index];\n        if (std::abs(previous.viewport.bottom - current.viewport.top) > 0.0001F ||\n            current.color.r > previous.color.r || current.color.g > previous.color.g ||\n            current.color.b > previous.color.b ||\n            std::abs(current.color.b - previous.color.b) > 0.01F)\n        {\n            return false;\n        }\n    }\n''',
    "abyss band checks")
text = replace_once(
    text,
    '''    const auto strategic = BuildStrategicSeabedPresentationModel();\n    if (!strategic || strategic->primitives.size() != 1U ||\n        strategic->primitives[0].vertices.size() != 192U ||\n        strategic->primitives[0].indices.size() != 288U ||\n        std::abs(strategic->bounds.minimum.y - M5StrategicSeabedExtrusionBottomYMeters) > 0.001F)\n''',
    '''    // Tactical context preserves the accepted local profile at the centre and descends into deep water\n    // away from it; the wide LOD therefore cannot become a flat replacement floor.\n    if (M5StrategicSeabedProfile.size() != 28U ||\n        M5StrategicSeabedProfile.front().yMeters >= -700.0F ||\n        M5StrategicSeabedProfile.back().yMeters >= -700.0F ||\n        M5StrategicSeabedProfile[7].xMeters != -400.0F ||\n        M5StrategicSeabedProfile[7].yMeters != -160.0F ||\n        M5StrategicSeabedProfile[15].xMeters != 0.0F ||\n        M5StrategicSeabedProfile[15].yMeters != -220.0F ||\n        M5StrategicSeabedProfile[20].xMeters != 400.0F ||\n        M5StrategicSeabedProfile[20].yMeters != -165.0F)\n    {\n        return false;\n    }\n\n    const auto strategic = BuildStrategicSeabedPresentationModel();\n    if (!strategic || strategic->primitives.size() != 1U ||\n        strategic->primitives[0].vertices.size() != 324U ||\n        strategic->primitives[0].indices.size() != 486U ||\n        std::abs(strategic->bounds.minimum.y - M5StrategicSeabedExtrusionBottomYMeters) > 0.001F)\n''',
    "strategic model checks")
path.write_text(text, encoding="utf-8")

# Keep the temporary script out of the production commit.
Path('.github/m5_v13_tactical_fix.py').unlink(missing_ok=True)
