if(NOT DEFINED DEEPRUN_P700_SOURCE_DIR OR NOT DEFINED DEEPRUN_P700_DESTINATION_DIR)
    message(FATAL_ERROR "StageP700Runtime requires source and destination directories")
endif()

set(model "${DEEPRUN_P700_SOURCE_DIR}/P700_Granit.glb")
set(metadata "${DEEPRUN_P700_SOURCE_DIR}/P700.asset.json")
set(authoring "${DEEPRUN_P700_SOURCE_DIR}/P700.authoring.json")
foreach(path IN LISTS model metadata authoring)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "P-700 runtime staging input is missing: ${path}")
    endif()
endforeach()

file(READ "${metadata}" metadata_json)
string(JSON schema_version GET "${metadata_json}" schemaVersion)
string(JSON asset_id GET "${metadata_json}" assetId)
string(JSON coordinate_contract GET "${metadata_json}" coordinateContract)
string(JSON expected_glb_sha GET "${metadata_json}" glbSha256)
string(JSON legal_status GET "${metadata_json}" licenseStatus)
if(NOT schema_version EQUAL 1 OR NOT asset_id STREQUAL "P700")
    message(FATAL_ERROR "P-700 runtime staging rejected unexpected metadata identity/schema")
endif()
if(NOT coordinate_contract STREQUAL "+X forward; +Y port; +Z up; 1 BU = 1 m")
    message(FATAL_ERROR "P-700 runtime staging rejected unexpected coordinate contract")
endif()
if(NOT legal_status STREQUAL "SHIPPING BLOCKED PENDING LEGAL REVIEW")
    message(FATAL_ERROR "P-700 runtime staging requires the current explicit legal-status marker")
endif()
file(SHA256 "${model}" actual_glb_sha)
string(TOUPPER "${actual_glb_sha}" actual_glb_sha)
string(TOUPPER "${expected_glb_sha}" expected_glb_sha)
if(NOT actual_glb_sha STREQUAL expected_glb_sha)
    message(FATAL_ERROR "P-700 runtime GLB SHA-256 does not match P700.asset.json")
endif()

file(READ "${authoring}" authoring_json)
string(JSON authoring_schema GET "${authoring_json}" schemaVersion)
string(JSON root_name GET "${authoring_json}" root)
string(JSON animation_name GET "${authoring_json}" animation name)
string(JSON start_frame GET "${authoring_json}" animation startFrame)
string(JSON end_frame GET "${authoring_json}" animation endFrame)
string(JSON surface_count LENGTH "${authoring_json}" movableSurfaces)
if(NOT authoring_schema EQUAL 1 OR NOT root_name STREQUAL "P700_ROOT" OR
   NOT animation_name STREQUAL "P700_Deploy" OR NOT start_frame EQUAL 1 OR NOT end_frame EQUAL 41 OR
   NOT surface_count EQUAL 6)
    message(FATAL_ERROR "P-700 runtime staging rejected unexpected authoring/deployment contract")
endif()

file(MAKE_DIRECTORY "${DEEPRUN_P700_DESTINATION_DIR}")
file(COPY_FILE "${model}" "${DEEPRUN_P700_DESTINATION_DIR}/P700_Granit.glb" ONLY_IF_DIFFERENT)
file(COPY_FILE "${metadata}" "${DEEPRUN_P700_DESTINATION_DIR}/P700.asset.json" ONLY_IF_DIFFERENT)
file(COPY_FILE "${authoring}" "${DEEPRUN_P700_DESTINATION_DIR}/P700.authoring.json" ONLY_IF_DIFFERENT)
