if(NOT DEFINED DEEPRUN_ANTEY_SOURCE_DIR OR NOT DEFINED DEEPRUN_ANTEY_DESTINATION_DIR)
    message(FATAL_ERROR "DEEPRUN_ANTEY_SOURCE_DIR and DEEPRUN_ANTEY_DESTINATION_DIR are required")
endif()

cmake_path(ABSOLUTE_PATH DEEPRUN_ANTEY_SOURCE_DIR NORMALIZE OUTPUT_VARIABLE source_dir)
cmake_path(ABSOLUTE_PATH DEEPRUN_ANTEY_DESTINATION_DIR NORMALIZE OUTPUT_VARIABLE destination_dir)
if(source_dir STREQUAL destination_dir)
    message(FATAL_ERROR "Antey runtime staging source and destination must differ")
endif()

set(required_files Antey.glb Antey.asset.json Antey.authoring.json)
foreach(required_file IN LISTS required_files)
    if(NOT EXISTS "${source_dir}/${required_file}")
        message(FATAL_ERROR "Antey runtime staging requires '${source_dir}/${required_file}'")
    endif()
endforeach()

function(require_json_value json_text label output)
    string(JSON value ERROR_VARIABLE json_error GET "${json_text}" ${ARGN})
    if(NOT json_error STREQUAL "NOTFOUND")
        message(FATAL_ERROR "Antey runtime staging invalid ${label}: ${json_error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(require_json_length json_text label expected_length)
    string(JSON length ERROR_VARIABLE json_error LENGTH "${json_text}" ${ARGN})
    if(NOT json_error STREQUAL "NOTFOUND" OR NOT length EQUAL expected_length)
        message(FATAL_ERROR "Antey runtime staging invalid ${label}")
    endif()
endfunction()

file(READ "${source_dir}/Antey.asset.json" asset_json)
require_json_value("${asset_json}" "Antey.asset.json schemaVersion" asset_schema schemaVersion)
require_json_value("${asset_json}" "Antey.asset.json assetId" asset_id assetId)
require_json_value("${asset_json}" "Antey.asset.json name" asset_name name)
require_json_value("${asset_json}" "Antey.asset.json coordinateContract" coordinate_contract coordinateContract)
require_json_value("${asset_json}" "Antey.asset.json technicalAssetStatus" technical_status technicalAssetStatus)
require_json_value("${asset_json}" "Antey.asset.json userVisualApproval" visual_status userVisualApproval)
require_json_value("${asset_json}" "Antey.asset.json glbSha256" expected_glb_hash glbSha256)
if(NOT asset_schema EQUAL 1 OR NOT asset_id STREQUAL "C0 Player Submarine" OR NOT asset_name STREQUAL "Antey" OR
   NOT coordinate_contract STREQUAL "+X bow; +Y port; +Z up; 1 BU = 1 m" OR NOT technical_status STREQUAL "ACCEPTED" OR
   NOT visual_status STREQUAL "PASS")
    message(FATAL_ERROR "Antey runtime staging rejected an unexpected production asset contract")
endif()
foreach(lod IN ITEMS LOD0 LOD1 LOD2 LOD3)
    require_json_value("${asset_json}" "Antey.asset.json ${lod}" lod_objects lods ${lod} objects)
    require_json_value("${asset_json}" "Antey.asset.json ${lod}" lod_vertices lods ${lod} vertices)
    require_json_value("${asset_json}" "Antey.asset.json ${lod}" lod_triangles lods ${lod} triangles)
    if(lod_objects LESS 0 OR lod_vertices LESS 0 OR lod_triangles LESS 0)
        message(FATAL_ERROR "Antey runtime staging rejected negative ${lod} accounting")
    endif()
endforeach()

file(SHA256 "${source_dir}/Antey.glb" actual_glb_hash)
string(TOUPPER "${expected_glb_hash}" expected_glb_hash)
string(TOUPPER "${actual_glb_hash}" actual_glb_hash)
if(NOT actual_glb_hash STREQUAL expected_glb_hash)
    message(FATAL_ERROR "Antey runtime staging rejected GLB hash mismatch")
endif()

file(READ "${source_dir}/Antey.authoring.json" authoring_json)
require_json_value("${authoring_json}" "Antey.authoring.json schemaVersion" authoring_schema schemaVersion)
require_json_value("${authoring_json}" "Antey.authoring.json coordinateContract" authoring_coordinate coordinateContract)
if(NOT authoring_schema EQUAL 1 OR NOT authoring_coordinate STREQUAL "${coordinate_contract}")
    message(FATAL_ERROR "Antey runtime staging rejected an unexpected authoring metadata contract")
endif()
require_json_length("${authoring_json}" "P700 launchers" 24 p700Launchers)
require_json_length("${authoring_json}" "torpedo tubes" 6 torpedoTubes)
require_json_length("${authoring_json}" "propellers" 2 propellers)
require_json_length("${authoring_json}" "compartments" 10 compartments)
require_json_length("${authoring_json}" "collision records" 4 collision)
require_json_value("${authoring_json}" "buoyancy proxy" buoyancy_proxy buoyancyProxy)
if(buoyancy_proxy STREQUAL "")
    message(FATAL_ERROR "Antey runtime staging rejected an empty buoyancy proxy")
endif()
string(FIND "${authoring_json}" "HP_Antey_" legacy_marker_index)
if(NOT legacy_marker_index EQUAL -1)
    message(FATAL_ERROR "Antey runtime staging rejected legacy HP_Antey_ metadata")
endif()

file(REMOVE_RECURSE "${destination_dir}")
file(MAKE_DIRECTORY "${destination_dir}")
foreach(required_file IN LISTS required_files)
    file(COPY_FILE "${source_dir}/${required_file}" "${destination_dir}/${required_file}" ONLY_IF_DIFFERENT)
endforeach()
